openapi: 3.0.1
info:
  title: Nationalize
  # description: A plugin that estimates the nationality of a person based on a surname.
  version: 0.1.0
servers:
  - url: https://api.nationalize.io/
paths:
  /:
    get:
      operationId: getNationality
      # description: Gets the probable nationality given the person's surname.
      parameters:
        - name: name
          in: query
          description: The surname of the person
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK - Returns a list of properties
          content:
            application/json:
              schema:
                type: string
