openapi: 3.0.1
info:
  title: Nationalize
  version: 0.1.0
servers:
  - url: https://api.nationalize.io/
paths:
  /:
    get:
      operationId: getNationality
      parameters:
        - name: name
          in: query
          description: The surname of the person
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK - Returns a list of properties
          content:
            application/json:
              schema:
                type: string
